sudeo: required
services:
  - docker

before_install:
  - docker build -t michaelcalfee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michaelcalfee/react-test npm test -- --coverage

after_success:
  - docker build -t michaelcalfee/multi-client ./client
  - docker build -t michaelcalfee/multi-nginx ./nginx
  - docker build -t michaelcalfee/multi-server ./server
  - docker build -t michaelcalfee/multi-worker ./worker
  # Take those images and push them to Dockerhub
